version: "3.8"
services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
  backend:
    build: ./backend
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev