version: "3.8"
services:
  postgres:
    image: 'postgres'
    restart: always
    volumes: 
      - data:/data/db
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
        - ./backend:/app
    depends_on: 
      - postgres
  frontend: 
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend
volumes: 
  data: